# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oastools < Formula
  desc "OpenAPI Specification (OAS) tools for validation, parsing, converting, and joining specs."
  homepage "https://github.com/erraggy/oastools"
  version "1.45.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erraggy/oastools/releases/download/v1.45.1/oastools_Darwin_x86_64.tar.gz"
      sha256 "4a3b0f99f63c32c08536549b1ca5f534edbca237b1e55a0273c9b9e9802882f6"

      def install
        bin.install "oastools"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erraggy/oastools/releases/download/v1.45.1/oastools_Darwin_arm64.tar.gz"
      sha256 "5544a2a4a57b23f47b8fc7bf98512adff9b52cb899f3362eada68cd3c1071453"

      def install
        bin.install "oastools"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erraggy/oastools/releases/download/v1.45.1/oastools_Linux_x86_64.tar.gz"
      sha256 "bcd14af2d445e625c756da4445aea29889714cb67e7f32fd16d081d8e99a613e"
      def install
        bin.install "oastools"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erraggy/oastools/releases/download/v1.45.1/oastools_Linux_arm64.tar.gz"
      sha256 "3f483779f87c8897829c7204ecbacd3de40f780fcad16a8a14846134a4aab984"
      def install
        bin.install "oastools"
      end
    end
  end
end
