# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oastools < Formula
  desc "OpenAPI Specification (OAS) tools for validation, parsing, converting, and joining specs."
  homepage "https://github.com/erraggy/oastools"
  version "1.28.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erraggy/oastools/releases/download/v1.28.3/oastools_Darwin_x86_64.tar.gz"
      sha256 "16d67362ace9ca38b75f08c516ec71307d487cf8f367057c9313d5468f1f5b88"

      def install
        bin.install "oastools"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erraggy/oastools/releases/download/v1.28.3/oastools_Darwin_arm64.tar.gz"
      sha256 "99eb16708edec478f50cfd7c83a5d6d84f546201a912869acf311ba4beafac3a"

      def install
        bin.install "oastools"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erraggy/oastools/releases/download/v1.28.3/oastools_Linux_x86_64.tar.gz"
      sha256 "84db2dee34df37eacb1103e8895c8dc782cef6a7f68699726df787f89d62374c"
      def install
        bin.install "oastools"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erraggy/oastools/releases/download/v1.28.3/oastools_Linux_arm64.tar.gz"
      sha256 "0b2a5d4e06ba1e0dbbd6b56c7943e0afec0b6f9fb886dc741ffef5b1d06d9aa6"
      def install
        bin.install "oastools"
      end
    end
  end
end
