# This file was generated by GoReleaser. DO NOT EDIT.
cask "oastools" do
  name "oastools"
  desc "OpenAPI Specification (OAS) tools for validation, parsing, converting, and joining specs."
  homepage "https://github.com/erraggy/oastools"
  version "1.9.9-test"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oastools"

  on_macos do
    on_intel do
      url "https://github.com/erraggy/oastools/releases/download/v#{version}/oastools_Darwin_x86_64.tar.gz",
        verified: "github.com/erraggy/oastools"
      sha256 "32beaf7b6a3e1d1187acfc69c1813d66bcae938613acd12376cc32f8ce592d52"
    end
    on_arm do
      url "https://github.com/erraggy/oastools/releases/download/v#{version}/oastools_Darwin_arm64.tar.gz",
        verified: "github.com/erraggy/oastools"
      sha256 "de96107e637e96208676b40bdf21a1fa38026fbcf9aec6ad3809bd6ebf838781"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/erraggy/oastools/releases/download/v#{version}/oastools_Linux_x86_64.tar.gz",
        verified: "github.com/erraggy/oastools"
      sha256 "e9eaf18e4ac000e833e27adcebec272569b7c02c271e2ac7fe0f08bdb7381cfe"
    end
    on_arm do
      url "https://github.com/erraggy/oastools/releases/download/v#{version}/oastools_Linux_arm64.tar.gz",
        verified: "github.com/erraggy/oastools"
      sha256 "c421ff95500d80965ee6efd8f73b52454569899adff8680f5b42f0a8abb94d79"
    end
  end

  # No zap stanza required
end
