# This file was generated by GoReleaser. DO NOT EDIT.
cask "oastools" do
  name "oastools"
  desc "OpenAPI Specification (OAS) tools for validation, parsing, converting, and joining specs."
  homepage "https://github.com/erraggy/oastools"
  version "1.9.9-test"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oastools"

  on_macos do
    on_intel do
      url "https://github.com/erraggy/oastools/releases/download/v#{version}/oastools_Darwin_x86_64.tar.gz",
        verified: "github.com/erraggy/oastools"
      sha256 "4ed0b0398eebc618e78f6b77b46e58454a47ee043387530ae87094dca80dc5d4"
    end
    on_arm do
      url "https://github.com/erraggy/oastools/releases/download/v#{version}/oastools_Darwin_arm64.tar.gz",
        verified: "github.com/erraggy/oastools"
      sha256 "0f50b966d1135a045d91da7536cb5f71de4fba19ee52dc00c2666e55221e20bf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/erraggy/oastools/releases/download/v#{version}/oastools_Linux_x86_64.tar.gz",
        verified: "github.com/erraggy/oastools"
      sha256 "f4b195b727911abc055eb625b7c3f724be440edf20f47c3277e4dedd289fb2eb"
    end
    on_arm do
      url "https://github.com/erraggy/oastools/releases/download/v#{version}/oastools_Linux_arm64.tar.gz",
        verified: "github.com/erraggy/oastools"
      sha256 "8f0000147601bca5804c3089ff9a41bceb1a750234ba6a326528b6af6ce00035"
    end
  end

  # No zap stanza required
end
