# This file was generated by GoReleaser. DO NOT EDIT.
cask "oastools" do
  name "oastools"
  desc "OpenAPI Specification (OAS) tools for validation, parsing, converting, and joining specs."
  homepage "https://github.com/erraggy/oastools"
  version "1.9.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oastools"

  on_macos do
    on_intel do
      url "https://github.com/erraggy/oastools/releases/download/v#{version}/oastools_Darwin_x86_64.tar.gz",
        verified: "github.com/erraggy/oastools"
      sha256 "8a8cfefcbb22cd86c8b4869c3ade1e4a308478b62ff20d378086b1771e01a6cc"
    end
    on_arm do
      url "https://github.com/erraggy/oastools/releases/download/v#{version}/oastools_Darwin_arm64.tar.gz",
        verified: "github.com/erraggy/oastools"
      sha256 "94325baafd9ddc1ad2844574de489e7acbb6567fdc5bbb5befd5a6a6d80a4211"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/erraggy/oastools/releases/download/v#{version}/oastools_Linux_x86_64.tar.gz",
        verified: "github.com/erraggy/oastools"
      sha256 "c1c33ca6a86c19a82e3ad1513f6c4631c89d1114b77e4a13c0b94d5bd0a82ec8"
    end
    on_arm do
      url "https://github.com/erraggy/oastools/releases/download/v#{version}/oastools_Linux_arm64.tar.gz",
        verified: "github.com/erraggy/oastools"
      sha256 "893019add208383a5f5fcb876869a6c1c8cec1d4afdca1c409cd7ac316b144ee"
    end
  end

  # No zap stanza required
end
